import { createClient } from "@/lib/supabase/server";
import { requireUser } from "@/lib/auth";
import { getActiveMembership } from "@/lib/workspace";
import { PageHeader } from "@/components/ui/page-header";
import { Panel } from "@/components/ui/card";
import { Alert } from "@/components/ui/feedback";
import { ActivityList, type ActivityRow } from "@/components/activity-list";
import { logDataReadFailure } from "@/lib/server-logs";

// ============================================================
// NEXUS — ACTIVITY
// The workspace event log, written by database triggers. Read-only:
// nothing here is generated by the interface.
// ============================================================

export const metadata = {
  title: "Activity. NEXUS",
  description: "Everything that changed in your NEXUS workspace.",
};

export default async function ActivityPage() {
  const user = await requireUser();
  const supabase = await createClient();
  const { membership } = await getActiveMembership(supabase, user.id);
  const workspaceId = membership?.workspaceId ?? null;

  const result = workspaceId
    ? await supabase
        .from("activities")
        .select("id, entity_type, action, metadata, created_at, actor_id")
        .eq("workspace_id", workspaceId)
        .order("created_at", { ascending: false })
        .limit(100)
    : { data: [], error: null };

  // The UI shows an honest "feed unavailable" state; the runtime logs keep
  // the real error triple (code/message/hint) for the operator.
  logDataReadFailure("activity.feed", "error" in result ? result.error : null);

  const rows = (result.data ?? []) as ActivityRow[];

  // Resolve actor names in one query. Profiles that RLS hides simply stay
  // unresolved — the feed then uses the passive voice instead of a guess.
  const actorIds = Array.from(
    new Set(rows.map((row) => row.actor_id).filter((id): id is string => Boolean(id)))
  );

  const names = new Map<string, string>();
  if (actorIds.length > 0) {
    const { data: profiles } = await supabase
      .from("profiles")
      .select("id, display_name, username")
      .in("id", actorIds);

    for (const profile of profiles ?? []) {
      const name =
        (profile.display_name as string | null) ??
        (profile.username as string | null);
      if (name) names.set(profile.id as string, name);
    }
  }

  const activities: ActivityRow[] = rows.map((row) => ({
    ...row,
    actor: row.actor_id ? (names.get(row.actor_id) ?? null) : null,
  }));

  return (
    <div className="page-enter">
      <PageHeader
        title="Activity"
        count={activities.length}
        description="Every change recorded in this workspace, newest first. Human actions and NEXUS observations are shown separately."
      />

      {!workspaceId ? (
        <Alert tone="warning" className="mb-5">
          No active workspace is linked to this account.
        </Alert>
      ) : null}

      <Panel bodyClassName="p-0">
        <ActivityList
          activities={activities}
          unavailable={Boolean(result.error)}
        />
      </Panel>
    </div>
  );
}
