import type { Metadata } from "next";
import { getAdminAuditLog, parseAdminListQuery } from "@/lib/admin/activity-security";
import { AdminRefreshButton } from "@/components/admin/admin-refresh-button";
import { AdminPanel, AdminSectionTitle } from "@/components/admin/panel";
import { AdminEmptyState, AdminErrorState } from "@/components/admin/states";
import { AdminListToolbar, AdminPagination, AdminSelectFilter } from "@/components/admin/list-controls";
import { formatDateTime } from "@/lib/admin/format";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Audit Log", robots: { index: false, follow: false } };
const PATH = "/admin/audit-log";
const outcomes = [{ value: "all", label: "All outcomes" }, { value: "success", label: "Success" }, { value: "denied", label: "Denied" }, { value: "failed", label: "Failed" }];
export default async function AdminAuditLogPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const query = parseAdminListQuery(await searchParams, "outcome");
  const result = await getAdminAuditLog(query);
  return <div className="mx-auto flex w-full max-w-page flex-col gap-5"><header className="flex items-start justify-between gap-3"><div><h1 className="text-[22px] font-semibold text-admin-text">Audit Log</h1><p className="mt-1 text-[13px] text-admin-text-2">Append-only admin actions and access decisions from public.admin_audit_log.</p></div><AdminRefreshButton /></header><AdminListToolbar pathname={PATH} query={{ ...query, outcome: query.filter, status: "all", sort: "created_at", direction: "desc" } as never} hasActiveFilters={!!query.search || query.filter !== "all"}><AdminSelectFilter id="audit-outcome" name="outcome" label="Outcome" value={query.filter} options={outcomes} /></AdminListToolbar>{result.state === "unavailable" ? <AdminPanel><AdminErrorState error={result.error} /></AdminPanel> : result.state === "empty" ? <AdminPanel><AdminEmptyState icon="history" title="No audit events match" description="The read succeeded and returned no events for these filters." /></AdminPanel> : <AdminPanel padded={false}><div className="p-4"><AdminSectionTitle title="Audit events" description={`${result.payload.total} immutable events matched; newest first.`} /></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-[12.5px]"><caption className="sr-only">Admin audit events</caption><thead><tr className="border-y border-admin-border font-mono text-[10px] uppercase text-admin-text-3"><th scope="col" className="px-4 py-2">Action</th><th scope="col" className="px-4 py-2">Actor</th><th scope="col" className="px-4 py-2">Outcome</th><th scope="col" className="px-4 py-2">Target</th><th scope="col" className="px-4 py-2">Created</th></tr></thead><tbody>{result.payload.items.map((item) => <tr key={String(item.id)} className="border-b border-admin-border/60"><td className="px-4 py-2.5 text-admin-text">{String(item.action)}</td><td className="px-4 py-2.5 text-admin-text-2">{String(item.actor_email ?? "Deleted account")}</td><td className="px-4 py-2.5 text-admin-text-2">{String(item.outcome)}</td><td className="px-4 py-2.5 text-admin-text-2">{String(item.target_type ?? "—")}</td><td className="px-4 py-2.5 font-mono text-[11px] text-admin-text-3">{formatDateTime(String(item.created_at))}</td></tr>)}</tbody></table></div><div className="p-4"><AdminPagination pathname={PATH} query={{ ...query, outcome: query.filter, status: "all", sort: "created_at", direction: "desc" } as never} page={result.payload.page} total={result.payload.total} pageSize={result.payload.page_size} unitLabel="audit events" /></div></AdminPanel>}</div>;
}
