import type { Metadata } from "next";
import { LegalDocumentLayout } from "@/components/legal/legal-layout";
import { PRIVACY_TOC } from "@/components/legal/legal-data";
import {
  LegalSection,
  LegalSectionTitle,
  LegalSubsectionTitle,
  LegalParagraph,
  LegalList,
  LegalListItem,
  LegalCallout,
  LegalContactBox,
} from "@/components/legal/legal-ui";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "Learn how NEXUS collects, handles, stores, and protects your workspace data, personal information, and operational context.",
  alternates: { canonical: "/privacy" },
  openGraph: {
    url: "/privacy",
    title: "Privacy Policy · NEXUS",
    description: "Detailed breakdown of data collection, Row-Level Security isolation, AI processing, and privacy rights.",
  },
};

export default function PrivacyPage() {
  return (
    <LegalDocumentLayout docId="privacy" toc={PRIVACY_TOC}>
      {/* 1. Introduction & Controller */}
      <LegalSection id="1-introduction-controller">
        <LegalSectionTitle>1. Introduction & Data Controller</LegalSectionTitle>
        <LegalParagraph>
          At NEXUS, we recognize that the operational data you entrust to our intelligent workspace
          represents your organization&rsquo;s core productivity and strategy. We are committed to
          protecting your personal data, maintaining strict workspace isolation, and operating with
          complete transparency regarding how information is processed.
        </LegalParagraph>
        <LegalParagraph>
          This Privacy Policy describes the policies and practices of{" "}
          <strong>[LEGAL ENTITY NAME]</strong> (&ldquo;NEXUS&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;,
          or &ldquo;our&rdquo;) acting as the data controller regarding the collection, use, storage,
          and disclosure of information collected through our web applications, APIs, and services.
        </LegalParagraph>
      </LegalSection>

      {/* 2. Principles */}
      <LegalSection id="2-principles">
        <LegalSectionTitle>2. Principles of Data Protection</LegalSectionTitle>
        <LegalParagraph>
          Our architecture and data processing workflows are guided by foundational principles:
        </LegalParagraph>
        <LegalList>
          <LegalListItem>
            <strong>Data Minimization:</strong> We only collect information strictly required to
            deliver workspace collaboration, operational signals, and intelligence capabilities.
          </LegalListItem>
          <LegalListItem>
            <strong>Tenant Isolation:</strong> Data belonging to one workspace is cryptographically
            and logically segregated from other workspaces using PostgreSQL Row-Level Security (RLS).
          </LegalListItem>
          <LegalListItem>
            <strong>Purpose Limitation:</strong> Workspace records and user content are never sold,
            rented, or utilized for cross-site behavioral profiling or third-party marketing.
          </LegalListItem>
          <LegalListItem>
            <strong>Transparent AI Governance:</strong> AI models operate on explicit, verified
            workspace snapshots; mutations are never executed without human verification.
          </LegalListItem>
        </LegalList>
      </LegalSection>

      {/* 3. Categories of Data */}
      <LegalSection id="3-data-collected">
        <LegalSectionTitle>3. Categories of Data We Collect</LegalSectionTitle>
        <LegalParagraph>
          We collect the following categories of data when you register and interact with NEXUS:
        </LegalParagraph>

        <LegalSubsectionTitle>3.1 Account & Identity Information</LegalSubsectionTitle>
        <LegalList>
          <LegalListItem>
            <strong>Authentication Credentials:</strong> Email address, cryptographically hashed
            passwords (managed exclusively by Supabase Auth), or OAuth provider identifiers (such as
            Google OAuth profile IDs).
          </LegalListItem>
          <LegalListItem>
            <strong>Profile Information:</strong> Optional display name, chosen username handle,
            avatar image URL, bio, and professional job title.
          </LegalListItem>
          <LegalListItem>
            <strong>Onboarding State:</strong> Onboarding intent and non-blocking setup checklist
            progress stored on the user profile.
          </LegalListItem>
        </LegalList>

        <LegalSubsectionTitle>3.2 Workspace & Operational Data</LegalSubsectionTitle>
        <LegalParagraph>
          Data generated by users while organizing work within NEXUS:
        </LegalParagraph>
        <LegalList>
          <LegalListItem>
            <strong>Workspaces:</strong> Workspace title, unique slug identifier, icon, color
            metadata, and role assignments (owner, admin, member, viewer).
          </LegalListItem>
          <LegalListItem>
            <strong>Projects & Tasks:</strong> Project names, descriptions, due dates, statuses,
            progress scores; Task titles, descriptions, priorities (low, medium, high, urgent),
            execution statuses (todo, in progress, in review, blocked, done, cancelled), due dates,
            completion timestamps, and task dependency relationships.
          </LegalListItem>
          <LegalListItem>
            <strong>Strategic Goals:</strong> Goal titles, target dates, progress tracking metrics,
            and status indicators.
          </LegalListItem>
          <LegalListItem>
            <strong>Audit Activity Stream:</strong> Automated system logs recording entity mutations
            (e.g., project creation, task status updates, goal completions) including actor UUID,
            action type, and timestamp.
          </LegalListItem>
          <LegalListItem>
            <strong>Notifications:</strong> In-app notifications regarding assigned tasks, workspace
            invitations, and system updates.
          </LegalListItem>
        </LegalList>

        <LegalSubsectionTitle>3.3 Intelligence & AI Context State</LegalSubsectionTitle>
        <LegalList>
          <LegalListItem>
            <strong>Working Memory:</strong> Structured short-term context (recent entity queries,
            last referenced items) and durable preferences explicitly requested by the user.
          </LegalListItem>
          <LegalListItem>
            <strong>Proactive Signals:</strong> Structured evidence-based operational signals (such
            as blocked task detections, overdue risks, score breakdowns, and suggested actions).
          </LegalListItem>
          <LegalListItem>
            <strong>Operational Missions:</strong> Multi-step operational objectives, planned steps,
            and next-best-action execution states.
          </LegalListItem>
        </LegalList>

        <LegalSubsectionTitle>3.4 Technical & Device Telemetry</LegalSubsectionTitle>
        <LegalParagraph>
          Standard HTTP request data including IP address (logged temporarily for rate limiting and
          DDoS protection), browser user agent, operating system type, and strictly necessary
          authentication session cookies.
        </LegalParagraph>
      </LegalSection>

      {/* 4. How We Use Data */}
      <LegalSection id="4-how-we-use-data">
        <LegalSectionTitle>4. How We Use Collected Data</LegalSectionTitle>
        <LegalParagraph>We process your data for the following specific purposes:</LegalParagraph>
        <LegalList>
          <LegalListItem>
            <strong>Service Delivery:</strong> Authenticating users, maintaining sessions, routing
            requests to isolated workspaces, and executing project management workflows.
          </LegalListItem>
          <LegalListItem>
            <strong>Signal Detection & Prioritization:</strong> Computing deterministic project health
            indexes, surfacing blocked work dependencies, and prioritizing urgent deadlines.
          </LegalListItem>
          <LegalListItem>
            <strong>AI Assistance:</strong> Synthesizing workspace summaries, generating daily
            operational plans, and proposing reviewable next actions upon user request.
          </LegalListItem>
          <LegalListItem>
            <strong>Security & Compliance:</strong> Enforcing plan resource limits, detecting
            fraudulent access attempts, preventing abusive scraping, and defending multi-tenant
            infrastructure.
          </LegalListItem>
          <LegalListItem>
            <strong>Platform Communication:</strong> Sending critical transactional notices, password
            reset links, and email confirmation messages.
          </LegalListItem>
        </LegalList>
      </LegalSection>

      {/* 5. AI Processing */}
      <LegalSection id="5-ai-processing">
        <LegalSectionTitle>5. AI Processing & NEXUS Intelligence</LegalSectionTitle>
        <LegalParagraph>
          NEXUS Intelligence combines an internal deterministic reasoning engine with optional
          external Large Language Models (OpenAI and Anthropic).
        </LegalParagraph>
        <LegalSubsectionTitle>5.1 Prompt Construction & Data Flow</LegalSubsectionTitle>
        <LegalParagraph>
          When you submit a natural language query or request a briefing, NEXUS constructs a compact,
          structured prompt containing verified facts from your active workspace (project titles, task
          statuses, due dates, and activity logs). This context is transmitted securely via TLS to the
          configured AI provider API.
        </LegalParagraph>
        <LegalSubsectionTitle>5.2 Privacy Commitments Regarding AI</LegalSubsectionTitle>
        <LegalList>
          <LegalListItem>
            <strong>No Public Model Training:</strong> Workspace data transmitted to external LLM
            providers via enterprise API agreements is not used to train or refine public foundation
            models without your explicit, separate authorization.
          </LegalListItem>
          <LegalListItem>
            <strong>Deterministic Fallback:</strong> If no external AI provider is configured, or in
            the event of network timeouts, NEXUS automatically falls back to its built-in deterministic
            reasoning engine without sending data externally.
          </LegalListItem>
          <LegalListItem>
            <strong>Read-Only Analysis:</strong> The AI provider can only propose read queries or
            draft actions. It possesses no direct database write permissions.
          </LegalListItem>
        </LegalList>
        <LegalCallout icon="ai" title="Assistive Intelligence">
          NEXUS Intelligence operates as an operational assistant. It cannot access data outside your
          authenticated workspace membership, and all proposed database mutations require human
          confirmation.
        </LegalCallout>
      </LegalSection>

      {/* 6. Legal Bases */}
      <LegalSection id="6-legal-bases">
        <LegalSectionTitle>6. Legal Bases for Processing</LegalSectionTitle>
        <LegalParagraph>
          Under European data protection laws (including the GDPR) and comparable international
          standards, we process your personal data under the following legal bases:
        </LegalParagraph>
        <LegalList>
          <LegalListItem>
            <strong>Performance of Contract (Art. 6(1)(b) GDPR):</strong> Processing necessary to
            create your account, maintain your workspace, and provide the core NEXUS product.
          </LegalListItem>
          <LegalListItem>
            <strong>Legitimate Interests (Art. 6(1)(f) GDPR):</strong> Protecting system security,
            preventing fraud, enforcing plan limits, and maintaining database performance.
          </LegalListItem>
          <LegalListItem>
            <strong>Consent (Art. 6(1)(a) GDPR):</strong> When you explicitly choose to store custom
            working preferences or provide optional profile details (e.g., job title or avatar).
          </LegalListItem>
          <LegalListItem>
            <strong>Legal Obligation (Art. 6(1)(c) GDPR):</strong> Compliance with applicable tax,
            accounting, or statutory disclosure obligations.
          </LegalListItem>
        </LegalList>
      </LegalSection>

      {/* 7. Storage & Architecture */}
      <LegalSection id="7-storage-architecture">
        <LegalSectionTitle>7. Multi-Tenant Storage & Architecture</LegalSectionTitle>
        <LegalParagraph>
          NEXUS is engineered with a strict defense-in-depth security model:
        </LegalParagraph>
        <LegalList>
          <LegalListItem>
            <strong>Database Engine:</strong> Managed PostgreSQL hosted in enterprise cloud data
            centers provided by Supabase Inc.
          </LegalListItem>
          <LegalListItem>
            <strong>Row-Level Security:</strong> All database queries from the application layer are
            evaluated against security definer policies that verify authenticated membership in the
            requested workspace.
          </LegalListItem>
          <LegalListItem>
            <strong>Encryption:</strong> Data is encrypted in transit using Transport Layer Security
            (TLS 1.3) and encrypted at rest using industry-standard AES-256 encryption.
          </LegalListItem>
        </LegalList>
      </LegalSection>

      {/* 8. Data Sharing */}
      <LegalSection id="8-data-sharing">
        <LegalSectionTitle>8. Data Sharing & Third-Party Processors</LegalSectionTitle>
        <LegalParagraph>
          We do not sell, rent, or trade your personal or workspace data. We share information only
          with verified sub-processors necessary to run the Service:
        </LegalParagraph>
        <LegalList>
          <LegalListItem>
            <strong>Supabase Inc.:</strong> Cloud database hosting, user authentication, and data
            storage infrastructure.
          </LegalListItem>
          <LegalListItem>
            <strong>AI Model Providers (OpenAI, LLC / Anthropic, PBC):</strong> Natural language
            processing and context analysis when external AI features are invoked.
          </LegalListItem>
          <LegalListItem>
            <strong>Cloud Hosting & Edge CDN:</strong> Next.js edge runtime, hosting, and asset
            delivery infrastructure.
          </LegalListItem>
          <LegalListItem>
            <strong>Payment Gateways (e.g., FedaPay / Regional Processors):</strong> Payment token
            processing for subscription billing (when enabled).
          </LegalListItem>
        </LegalList>
        <LegalParagraph>
          All sub-processors are bound by strict Data Processing Agreements (DPAs) requiring
          confidentiality, robust security standards, and processing solely under our instructions.
        </LegalParagraph>
      </LegalSection>

      {/* 9. Data Retention */}
      <LegalSection id="9-data-retention">
        <LegalSectionTitle>9. Data Retention & Account Deletion</LegalSectionTitle>
        <LegalParagraph>
          We retain your personal data and workspace content for as long as your account remains
          active, or as needed to provide you with the Service.
        </LegalParagraph>
        <LegalParagraph>
          <strong>Account Deletion:</strong> When you delete your account or workspace through the
          settings interface, your profile, workspaces, projects, tasks, goals, signals, and working
          memory are deleted immediately from active production databases via database cascade
          triggers.
        </LegalParagraph>
        <LegalParagraph>
          <strong>Backup Cycles:</strong> Encrypted automated database backups are maintained for
          disaster recovery purposes for a rolling period of up to 30 days, after which they are
          permanently purged.
        </LegalParagraph>
      </LegalSection>

      {/* 10. Security Measures */}
      <LegalSection id="10-security-measures">
        <LegalSectionTitle>10. Security Measures & Incident Protocol</LegalSectionTitle>
        <LegalParagraph>
          We maintain rigorous administrative, technical, and physical safeguards to prevent
          unauthorized access, alteration, disclosure, or destruction of your data:
        </LegalParagraph>
        <LegalList>
          <LegalListItem>
            Strict PostgreSQL RLS policy enforcement at the database level;
          </LegalListItem>
          <LegalListItem>
            Cryptographic password hashing and secure tokenized authentication flows;
          </LegalListItem>
          <LegalListItem>
            Continuous audit logging of data mutations via security definer database triggers;
          </LegalListItem>
          <LegalListItem>
            Automated rate-limiting and session timeouts on sensitive authentication endpoints.
          </LegalListItem>
        </LegalList>
        <LegalParagraph>
          In the event of a confirmed security incident affecting your personal data, we will notify
          affected account owners and relevant supervisory authorities without undue delay in
          accordance with applicable legal requirements.
        </LegalParagraph>
      </LegalSection>

      {/* 11. User Rights */}
      <LegalSection id="11-user-rights">
        <LegalSectionTitle>11. User Rights & Data Subject Requests</LegalSectionTitle>
        <LegalParagraph>
          Depending on your geographical location and applicable privacy laws, you possess the
          following statutory rights regarding your personal data:
        </LegalParagraph>
        <LegalList>
          <LegalListItem>
            <strong>Right to Access:</strong> Request a copy of the personal data we hold about you.
          </LegalListItem>
          <LegalListItem>
            <strong>Right to Rectification:</strong> Correct inaccurate or incomplete profile and
            workspace records.
          </LegalListItem>
          <LegalListItem>
            <strong>Right to Erasure (&ldquo;Right to be Forgotten&rdquo;):</strong> Request the
            permanent deletion of your account and associated personal data.
          </LegalListItem>
          <LegalListItem>
            <strong>Right to Restriction & Objection:</strong> Object to or restrict specific data
            processing activities under certain conditions.
          </LegalListItem>
          <LegalListItem>
            <strong>Right to Data Portability:</strong> Obtain your structured workspace data in a
            machine-readable format.
          </LegalListItem>
        </LegalList>
        <LegalParagraph>
          To exercise any of these rights, you may utilize the built-in self-service controls in your
          workspace settings or submit a written request to <strong>[LEGAL CONTACT EMAIL]</strong>. We
          respond to all verified requests within thirty (30) days.
        </LegalParagraph>
      </LegalSection>

      {/* 12. International Transfers */}
      <LegalSection id="12-international-transfers">
        <LegalSectionTitle>12. International Data Transfers</LegalSectionTitle>
        <LegalParagraph>
          NEXUS and its third-party infrastructure providers operate globally. Your information may
          be transferred to and processed in countries outside your country of residence, where data
          protection laws may differ.
        </LegalParagraph>
        <LegalParagraph>
          Whenever we transfer personal data across international borders, we ensure adequate
          safeguards are implemented, including standard contractual clauses (SCCs) approved by the
          European Commission, adherence to international adequacy decisions, or equivalent legal
          mechanisms.
        </LegalParagraph>
      </LegalSection>

      {/* 13. Cookies */}
      <LegalSection id="13-cookies-storage">
        <LegalSectionTitle>13. Cookies & Local Storage Technologies</LegalSectionTitle>
        <LegalParagraph>
          NEXUS strictly limits the use of browser storage technologies to essential authentication
          session cookies and functional client-side preferences (such as command menu history and
          onboarding checklist progress). We do not deploy third-party advertising cookies, tracker
          pixels, or marketing scripts.
        </LegalParagraph>
        <LegalParagraph>
          For complete technical details on every cookie and storage key utilized by NEXUS, please
          consult our dedicated <a href="/cookies" className="text-text-primary underline">Cookie Policy</a>.
        </LegalParagraph>
      </LegalSection>

      {/* 14. Children's Privacy */}
      <LegalSection id="14-childrens-privacy">
        <LegalSectionTitle>14. Children&rsquo;s Privacy</LegalSectionTitle>
        <LegalParagraph>
          NEXUS is designed exclusively for business operators, teams, and professionals. We do not
          knowingly collect, solicit, or maintain personal data from individuals under the age of 18.
          If we become aware that personal information from a minor has been collected without verified
          parental consent, we will promptly delete such records from our databases.
        </LegalParagraph>
      </LegalSection>

      {/* 15. Changes */}
      <LegalSection id="15-policy-changes">
        <LegalSectionTitle>15. Changes to This Privacy Policy</LegalSectionTitle>
        <LegalParagraph>
          We may update this Privacy Policy periodically to reflect evolving features, operational
          practices, or regulatory requirements. Material revisions will be highlighted by updating
          the &ldquo;Last updated&rdquo; date at the top of this document and providing prominent
          notice within the NEXUS interface or via email.
        </LegalParagraph>
      </LegalSection>

      {/* 16. Contact */}
      <LegalSection id="16-contact-dpo">
        <LegalSectionTitle>16. Contact & Data Protection Inquiries</LegalSectionTitle>
        <LegalParagraph>
          If you have questions, feedback, or concerns regarding this Privacy Policy or our data
          protection standards, please contact our designated privacy officer:
        </LegalParagraph>

        <LegalContactBox />
      </LegalSection>
    </LegalDocumentLayout>
  );
}
